version: '3.4'

services:
  recipes_db:
    image: ${DOCKER_REGISTRY-}recipesdb
    build:
      context: .
      dockerfile: Recipes_DB/Dockerfile
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
    ports: ["1533:1433"]
    volumes:
      ["${APPDATA}/DockerVolumes/sqlserver:/var/opt/mssql/data"]
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

